# bot settings
bot_token: '8184530658:AAGVKieh3fuhno9B8vzQL_YGcKLsd37xHYQ' # support bot token
staffchat_id: '-4526689167' # eg. -123456789
owner_id: '6010444106'
spam_time: 300000 # time (in MS) in which user may send 5 messages
spam_cant_msg: 5

parse_mode: 'Markdown' # Experimental. Do not change unless you know what you are doing. Options: Markdown/MarkdownV2/HTML

allow_private: false # Allow / disallow option for staff to chat privately
direct_reply: false # Set this to true to just forward staff users to a user chat when allow_private
auto_close_tickets: true # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not
anonymous_replies: true # Include staff member name in response
show_auto_replied: false # Send auto replied msgs to staff chat
show_user_ticket: false # Show ticket id to user
autoreply_confirmation: true # Reply with language.confirmationMessage on each incoming message
clean_replies: false # Remove footer and header from response
pass_start: false # Pass /start command to support directly

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server

dev_mode: false # Enable/disable dev mode

# customize your language
language:
  startCommandText: 'Welcome in CoreGram Support Bot! Ask your question here.'
  faqCommandText: 'CoreGram: The Ultimate Telegram Marketing Tool'
  helpCommandText: "*Available commands:* /help /faq /id"
  helpCommandStaffText: "*Available commands:*\n
    /start - Get a little introduction \n
    /faq - Show frequently asked questions \n
    /open - *Staff* Shows a list of open tickets \n
    /reopen - *Staff* Reopen a closed ticket \n
    /close - *Staff* Reply to a ticket with this to close and unban \n
    /clear - *Staff* Closes all tickets \n
    /ban - *Staff* Ban a user from the chat \n
    /unban - *Staff* Unban a user"
  confirmationMessage: "Thank you for contacting us. We will answer as soon as possible. "
  blockedSpam: 'You sent quite a number of questions in the last while. Please calm down and wait until staff reviews them.'
  ticket: 'Ticket'
  closed: 'closed'
  acceptedBy: 'was accepted by'
  dear: 'Hi'
  regards: 'Regards,'
  from: 'from'
  language: 'Language'
  msg_sent: 'Message sent to user'
  file_sent: 'File sent to user'
  usr_with_ticket: 'User with ticket'
  banned: 'banned'
  replyPrivate: 'Reply in private'
  services: 'Select a service from the list below'
  customer: 'customer'
  msgForwarding: 'You messages will now be forwarded to vendors of the group: '
  back: 'Go back'
  whatSubCategory: 'Which subcategory describes your needs the best? '
  prvChatEnded: 'Private chat ended.'
  prvChatOpened: 'Private Chat opened with customer.'
  prvChatEnd: 'End Private chat'
  prvChatOpenedCustomer: 'Opened private chat'
  instructionsSent: 'Instructions were sent to you in private chat.'
  openTickets: 'Open Tickets'
  support: 'Support'
  prvChatOnly: 'This command can be used in private chat only.'
  ticketClosed: 'Your ticket was closed by our staff. You can open a new ticket at any time.'
  links: 'Direct support links'
  textFirst: 'Please send us a message before sending an image so that we can help you better.'
  ticketClosedError: 'You cannot reply to a closed ticket.'
  automatedReply: 'This is an automated reply.'
  automatedReplyAuthor: 'CoreGram Bot.'
  doesntHelp: 'This does not help.'
  automatedReplySent: 'Automated reply was send to the user.'
  ticketReopened: 'Ticket reopened.'
  regardsGroup: 'CoreGram Team'

autoreply:
  - question: 'hi'
    answer: "Welcome To CoreGram CoreGram is a Telegram marketing tool designed to help you automate member management, messaging, and tracking."
  - question: 'hello'
    answer: 'Welcome To CoreGram CoreGram is a Telegram marketing tool designed to help you automate member management, messaging, and tracking.'
  - question: 'help'
    answer: "Welcome To CoreGram CoreGram is a Telegram marketing tool designed to help you automate member management, messaging, and tracking."
# categories:
#  - name: "Category1"
#    subgroups:
#    - name: "Sub1"
#      group_id: "-12345678910"
#    - name: "Sub2"
#      group_id: "-12345678910"
#    - name: "Sub3"
#      group_id: "-12345678910"
#  - name: "Category2"
#    subgroups:
#    - name: "Sub4"
#      group_id: "-12345678910"
#    - name: "Sub5"
#      group_id: "-12345678910"
#    - name: "Sub6"
#      group_id: "-12345678910"
#  - name: "Category with no subcategories"
#    group_id: "-12345678910"
#  - name: "Admin Chat"
#    group_id: "-12345678910"
#  - name: "Other issues"
#    tag: "#other"
#    msg: "Please specify your order number and describe the problem in as much detail as possible"
#    group_id: "-12345678910"
#  - name: "Contact"
#    msg: "Check out our Website"

